-- Схема песочницы для сквозного прогона (локальная БД, не прод).
-- Создаёт минимальный набор таблиц, который нужен режиму `-full`:
--   static_initial_data_control_operations — заполняет load_init_data.py
--   sap_operations, sap_regions            — справочники (из CSV-дампов)
--   sap_control_operations_source          — исходные данные SAP (из CSV-дампа)
--   control_operations_aggregated_new      — итоговая таблица, её пишет .exe
--
-- Схема справочника уже в НОВОМ виде: input_operation_order / input_deadline —
-- text со списками через запятую, колонок alternative_* нет.

DROP TABLE IF EXISTS static_initial_data_control_operations;
DROP TABLE IF EXISTS control_operations_aggregated_new;
DROP TABLE IF EXISTS sap_control_operations_source;
DROP TABLE IF EXISTS sap_operations;
DROP TABLE IF EXISTS sap_regions;

CREATE TABLE static_initial_data_control_operations (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    culture_id            integer NOT NULL,
    t_material_id         integer NOT NULL,
    region_id             integer NOT NULL,
    season                text    NOT NULL,
    region_date           date,
    input_operation_order text,
    input_deadline        text,
    noinput_deadline      integer,
    "order"               integer NOT NULL,
    year                  integer NOT NULL
);

CREATE TABLE sap_operations (
    t_material     text NOT NULL,
    operation_name text,
    id             integer PRIMARY KEY
);

CREATE TABLE sap_regions (
    id   integer PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE sap_control_operations_source (
    id             integer PRIMARY KEY,
    culture_id     integer,
    t_material_id  integer,
    region_id      integer,
    pu_id          integer,
    higher_tm      text,
    season         text,
    calendar_day   date,
    planned_volume integer,
    actual_volume  integer,
    year           integer
);

-- Колонки и их порядок должны совпадать с insertIntoControlOperationsAggregated
-- в src/db/db.cpp. id генерируется базой; TRUNCATE ... RESTART IDENTITY в C++
-- требует именно identity-колонки.
CREATE TABLE control_operations_aggregated_new (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    culture_id    integer,
    region_id     integer,
    t_material_id integer,
    pu_id         integer,
    higher_tm     text,
    season        text,
    calendar_day  date,
    year          integer,
    actual_date   date,
    start_date    date,
    is_completed  boolean,
    is_started    boolean,
    sawing_date   date,
    resawing_date date,
    status        text,
    is_actual     text,
    minimal_date  date,
    "order"       integer
);

-- Индексы под запросы C++ (ORDER BY calendar_day, id и т.п.)
CREATE INDEX ix_socs_calendar_day ON sap_control_operations_source (calendar_day, id);
CREATE INDEX ix_sidco_order ON static_initial_data_control_operations ("order", culture_id, region_id);
